Update toolchain to 2023-02-16
Skip over all the nightlies from 2023-02-06 until 2023-02-15 as those
ICE when trying to build kani with:
```
error: internal compiler error: cannot relate constants (Const { ty: fn() -> usize {std::mem::size_of::<[T; N]>}, kind: Value(Branch([])) }, Const { ty: fn() -> usize {std::mem::size_of::<[T; _]>}, kind: Value(Branch([])) }) of different types: fn() -> usize {std::mem::size_of::<[T; N]>} != fn() -> usize {std::mem::size_of::<[T; _]>}
```

This issue was reported upstream as
https://github.com/rust-lang/rust/issues/107898, and fixed in
https://github.com/rust-lang/rust/pull/107940, which isn't part of any
of the above nightlies.

Doing this multi-day update also requires addressing:

Remove some superfluous type parameters from layout.rs https://github.com/rust-lang/rust/pull/107163
Introduce -Zterminal-urls to use OSC8 for error codes https://github.com/rust-lang/rust/pull/107838
s/eval_usize/eval_target_usize/ for clarity https://github.com/rust-lang/rust/pull/108029

Co-authored-by: Qinheping Hu <qinhh@amazon.com>